### ISSUE TITLE
CVE methods need tests

### ISSUE THREAD

**Issue by yesmar** [dyesmar/cve#1]
CVE ingestion is well-tested, but the `String`, `URL`, and `MarkdownLink` methods need tests.

**Comment by dyesmar** [comment]
Added `String` method test in commit dca5721.

**Comment by dyesmar** [comment]
Added `URL` method test in commit 6491c5a.

**Comment by dyesmar** [comment]
The comment in the `TestString` test case contained an error. It is fixed in c17c913.

**Comment by dyesmar** [comment]
> Added `String` method test in commit [dca5721](https://github.com/dyesmar/cve/commit/dca5721b49c60de83b7f2314a0b6aa6b8f901fe2).

The comment in the `TestString` test case contained an error. It is fixed in c17c913.

**Comment by dyesmar** [comment]
> Added `URL` method test in commit [6491c5a](https://github.com/dyesmar/cve/commit/6491c5ae01dfb00ae8420f2ff5018a7ad3145e93).

The code in the `TestURL` test case contained an error. It is fixed in 16934fe.
